---
title: "01_load"
format: html
---

### Libraries

```{r}
library("here")
library('dplyr')
library("tidyverse")
```

### Download data

```{r}
curl::curl_download(url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE41080&format=file", 
                    destfile = here("data","_raw","GSE41080_RAW.tar"))
```

### Expression

```{r}
untar(here("data","_raw","GSE41080_RAW.tar"), 
      exdir = here("data","expression"))
```

```{r}
expression_files <- list.files(here("data","expression"))
```

```{r}
data_expression <- read_delim(here("data","expression",
                                   expression_files[2:92]), 
                              id = "file", 
                              col_names = c("PROBE_ID",
                                            "NBEADS1",
                                            "Signal",
                                            "Pval",
                                            "NARRAYS",
                                            "ARRAY_STDEV",
                                            "BEAD_STDERR",
                                            "NBEADS2",
                                            "SEARCH_KEY"), 
                              skip = 1,
                              na = "NaN")
data_expression <- mutate(data_expression, file = str_extract(file, "GSM[0-9]+"))
```

```{r}
write_tsv(data_expression, here("data","01_expression_dat.tsv.gz"))
```

### Meta data

```{r}
metadata <- read_delim("../data/_raw/msb201315-s2.csv", delim = ',', na = "NA" , n_max= 89)
```

```{r}
dir.create(here("data","01_load"), recursive = TRUE, showWarnings = FALSE)

metadata <- metadata %>%
  select(-starts_with("Season"), -starts_with("VacType"))

write_tsv(metadata, here("data", "01_load", "01_dat_load.tsv"))
```
