---
title: "02_clean"
format: html
---

## Libraries

```{r}
#| message: false

library("here")
library("tidyverse")
```

## Expression data

```{r}
data_expression <- read_tsv(here("data", "01_expression_dat_load.tsv.gz"),
                            show_col_types = FALSE) |> 
  select(file, PROBE_ID, Signal, Pval) |> 
  filter(file != "GSM1008315" & file != "GSM1008340")
```

```{r}
data_expression <- data_expression |>
  group_by(PROBE_ID) |> 
  nest() |> 
  mutate(Avg_Pval = map_dbl(.x = data, 
                            .f = ~mean(pull(.x, Pval)))) |> 
  unnest(cols = c(data)) |> 
  ungroup() |>
  filter(Avg_Pval < 0.05) |> 
  select(-Avg_Pval)
```

```{r}
write_tsv(data_expression, here("data", "02_expression_dat_clean.tsv.gz"))
```

## Metadata

```{r}
dir.create(here("data"), recursive = TRUE, showWarnings = FALSE)

metadata <- metadata |> 
  select(-starts_with("Season"),
    -starts_with("VacType"),
    -Prior_vac,
    -VACCOUNT,
    -FLU_EVR,
    -FLU_HOSP)

write_tsv(metadata, here("data", "02_meta_dat_clean.tsv"))
```
